### ISSUE TITLE
Local Storage cache key is `undefined`

### ISSUE THREAD

**Issue by radarseven** [spatie/vue-save-state#7]
Hey Team,

First off, thanks for this plugin! This will be really useful.

I've gone through the setup in the readme and have implemented in a Vue component in my application. The state is being saved to local storage, however, the key is being set to `undefined`. I am declaring a key in my component in this way:

```
export default {
  import saveState from 'vue-save-state';
  // ...
  mixins: [saveState],
  // ...
  methods: {
      getSaveStateConfig() {
        return {
          'vueProjectGrid': 'ProjectGrid',
        };
      },
  },
  // ...
}
```

And here's a screenshot from Chrome devtools:

![screenshot 2017-07-26 11 26 03](https://user-images.githubusercontent.com/93583/28629922-d07377c0-71f6-11e7-91bc-711d1c7e53ed.png)

Any help you could provide would be much appreciated.

**Comment by radarseven** [comment]
Sorry, dumb mistake on my part. I realized the method should be the following:

```
 methods: {
      getSaveStateConfig() {
        return {
          'cacheKey': 'vueProjectGrid',
        };
      },
  },
```

**Comment by khalwat** [comment]
I made the same mistake; I think the documentation is a little unclear.
